export type Locale = "zh" | "en";

/** 连续性问题 label 本地化（P0.4：UI 按 locale 渲染，code 保持稳定） */
export const issueLabels: Record<Locale, Record<string, string>> = {
  zh: {
    "IDENTITY.COUNT": "角色数量", "IDENTITY.STRICT_NOT_REFERENCED": "强锁角色未引用", "IDENTITY.ALWAYS_VISIBLE_UNVERIFIED": "始终可见未验证", "IDENTITY.DUPLICATE": "角色重复", "IDENTITY.MARKERS_MISSING": "独特标记缺失",
    "SCENE.ENVIRONMENT_UNLOCKED": "环境未锁定", "SCENE.WEATHER_MISSING": "缺少天气",
    "TECHNICAL.NEGATIVE_EMPTY": "负面词为空", "TECHNICAL.CAMERA_MISSING": "相机/镜头型号缺失", "TECHNICAL.PROFILE_MISSING": "技术 Profile 缺失",
    "SPATIAL.AXIS_CONFLICT": "轴线冲突", "SPATIAL.AXIS_BREAK_INTENTIONAL": "故意越轴", "SPATIAL.LOCATION_MISSING": "地点资产缺失", "SPATIAL.ORDER_EXTRA": "站位含非参与者", "SPATIAL.ORDER_MISSING": "参与者缺位", "SPATIAL.WEAK_ANCHOR": "弱空间锚点",
    "PROP.REFERENCE_MISSING": "道具引用缺失", "PROP.NOT_HELD_BEFORE_TRIGGER": "触发前未持有", "PROP.STATE_REGRESSION": "终态回退", "PROP.STATE_UNPRODUCED": "状态未由前镜产生",
    "CAUSALITY.TARGET_MISSING": "攻击目标缺失", "CAUSALITY.FORBIDDEN_TARGET": "禁止目标", "CAUSALITY.PRECONDITION_MISSING": "前置状态缺失",
    "AUDIO.PLAN_MISSING": "音频计划缺失", "AUDIO.DIALOGUE_UNSUBTITLED": "对白未加字幕", "AUDIO.CONFLICT": "音乐误标为音效", "AUDIO.SOURCE_MISSING": "音乐来源缺失",
    "CAMERA.HANDHELD_DIGITAL": "数字手持词", "FILM.LOWLIGHT_NOTE": "低照度胶片提示", "LIGHTING.CONFLICT": "光线冲突", "LIGHTING.DIRECTION_MISSING": "缺少光线方向", "OPTICS.FOV_OVERRIDDEN": "长镜头焦段被覆写", "OPTICS.BRAND_AS_PRIMARY": "品牌/焦距代替视场角", "OPTICS.MIXED_CONTENT_CLASS": "镜头语言与内容类别冲突", "PHYSICS.GROUND_CONTACT": "缺地面接触锚点",
    "ACTING.OBJECTIVE_MISSING": "角色目的缺失", "ACTING.OBSTACLE_OR_STAKES_MISSING": "阻碍/代价缺失", "ACTING.TACTIC_MONO": "策略单一", "ACTING.BEATS_FLAT": "节拍平直", "ACTING.EYE_LIFE_MISSING": "眼部生活缺失", "ACTING.DEAD_PAUSE": "空洞停顿", "ACTING.SUBTEXT_MISSING": "潜台词缺失", "ACTING.TRANSITION_CHAIN": "状态写成过渡", "ACTING.ENSEMBLE_SYNC": "群像同步反应", "ACTING.SCALE_BELOW_TARGET": "表演评分过低", "ACTING.INDICATION": "面具式表情", "ACTING.EMOTIONAL_RESET": "情绪瞬间复位", "ACTING.MASK_NO_CRACK": "冷静面具无裂缝", "ACTING.TIC_NO_TRIGGER": "抽动无触发", "ACTING.WARDROBE_IN_PROFILE": "母版混入服装/相机", "ACTING.VOICE_LOCK_MISSING": "声音锁缺失",
    "SPATIAL.GAZE_ORIENT_MISSING": "对白缺朝向/视线", "DIALOGUE.LIPS_RULE": "台词缺闭嘴锁", "DIALOGUE.TIMING_UNSPECIFIED": "台词缺时机规则", "AUDIO.VOICE_PROMPT_OMITTED": "台词角色缺声音锁", "CONTEXT.STALE_TAG": "陈旧 @资产引用", "CONTEXT.SCENE_NUMBER": "输出含场景编号",
  },
  en: {},
};

export type CopyZh = typeof copy.zh;
export type CopyEn = typeof copy.en;

export const copy = {
  zh: {
    project: "项目", newProject: "新建项目", scenes: "场景", addScene: "添加场景", character: "角色", addCharacter: "添加角色", reference: "参考图", addReference: "添加参考图", localProject: "本地项目", saved: "已保存",
    openProject: "打开项目", settings: "设置", compilePrompt: "编译提示词", environmentLocked: "环境锁定", referenceEnvironment: "参考图 / 环境", previewScene: "预览场景", shotList: "镜头列表", cuts: "个 CUT", addShot: "添加镜头",
    inspector: "检查器", noShot: "未选择镜头", camera: "摄影机", cameraModel: "相机型号", framing: "景别", lens: "镜头", lensModel: "镜头型号", movement: "运动", performance: "表演", action: "动作", acting: "演技", continuity: "连续性", characterLocked: "角色锁定", screenDirection: "画面方向",
    promptEditor: "提示词编辑器", localCompiler: "本地编译器", copyPrompt: "复制提示词", export: "导出", generate: "生成", addShotHint: "添加镜头以开始镜头设计。", promptCopied: "提示词已复制到剪贴板。", promptCompiled: "结构化提示词已编译。", promptRebuilt: "已从结构化字段重新构建提示词。", newProjectCreated: "已创建新项目。", projectImported: "项目已导入。", invalidProject: "该文件不是有效的 CinePrompt JSON 导出。", addCharacterHint: "角色创建功能将在下一阶段接入。", addReferenceHint: "参考图分析将在 AI Provider 层接入。",
    untitledFilm: "未命名影片", sceneName: "场景", newSceneName: "新场景", shotName: "镜头", defineAction: "定义镜头中的动作。", naturalPerformance: "自然、克制的表演。", environment: "环境", weather: "天气", movementDirection: "运动方向",
    static: "固定", handheld: "手持", steadicam: "斯坦尼康", dolly: "移轨", tracking: "跟拍", crane: "摇臂", directionLTR: "从左到右", directionRTL: "从右到左",
    projectName: "项目名", masterStyle: "大师风格", selectStyle: "选择大师风格", uploadImage: "上传图片", replaceImage: "更换图片", uploadAudio: "上传音频", imageUploaded: "角色图片已上传。", audioUploaded: "角色音频已上传。", uploadFailed: "文件读取失败，请重试。", metaLocation: "地点", metaTime: "时间", metaWeather: "天气", metaDuration: "时长", negativePrompt: "负面提示词", negativeHint: "留空时使用默认约束", negativePlaceholder: "不想出现在画面中的元素，逐项用逗号分隔…",
    sceneLock: "场景锁定", notes: "补充描述", notesPlaceholder: "场景环境细节、氛围、道具等补充说明…", deleteScene: "删除场景", seconds: "秒", keepOneScene: "至少保留一个场景。",
    assetLibrary: "资产库", assetTabCharacter: "角色", assetTabLocation: "地点", assetTabProp: "道具", assetTabReference: "风格/声音参考", addAsset: "添加资产", emptyAssets: "资产库为空，点击「+ 添加」创建角色、地点或道具。",
    assetName: "名称", assetNamePlaceholder: "REIN / BAKERY INTERIOR / boombox", assetNotes: "用户备注（仅 AI 参考）", assetNotesPlaceholder: "补充性格、动机、声音或资产用途；不会输出到最终提示词…", assetNotesZhPlaceholder: "补充性格、动机、声音或资产用途；仅供 AI 参考，不会输出到最终提示词…", assetDescription: "描述（英文 canonical）", assetDescriptionPlaceholder: "输入或粘贴英文描述，例如：Slim woman in a vintage bomber jacket.",
    assetDescriptionZh: "中文描述", assetDescriptionZhPlaceholder: "用中文描述这张图（AI 会自动对照参考图填好中文与英文 canonical）…", aiFillDetails: "AI 填写详细", aiFillDone: "AI 已根据参考图填好卡片描述，可继续微调。", aiFillFailed: "AI 填写失败：", aiNotConfigured: "请先在右上角「设置 → API 设置」配置大语言模型后再使用 AI 填写。", aiFillNeedsImage: "请先上传至少一张参考图，AI 需要看图才能填写详细。",
    useFor: "用途", useForFace: "脸部身份", useForBody: "身体体型", useForWardrobe: "服装", useForPropAppearance: "道具外观", useForEnvironment: "场景布局", useForAppearanceOnly: "仅外观参考",
    ignoreLabel: "忽略", ignorePose: "姿势", ignoreBackground: "背景", ignoreLighting: "光线", ignoreComposition: "构图", ignoreExpression: "表情",
    lockLevel: "锁定级别", lockNone: "未锁定", lockSoft: "建议锁定", lockStrict: "强锁定",
    uniqueMarkers: "独特标记", uniqueMarkerPlaceholder: "例如：左眼一道疤痕（Enter 添加）", alwaysVisible: "始终可见", alwaysVisiblePlaceholder: "例如：双手始终戴着黑色皮手套（Enter 添加）",
    deleteAsset: "删除资产", assetAdded: "已添加资产。", assetDeleted: "已删除资产。", assetKindCharacter: "角色", assetKindLocation: "地点", assetKindProp: "道具", assetKindStyleRef: "风格参考", assetKindAudioRef: "声音参考",
    referenceImage: "参考图", replaceReference: "更换参考图", identityLockSection: "身份强锁", characterCountLock: "角色数量锁", countLockPlaceholder: "不锁定", openExample: "载入示例", exampleLoaded: "已载入示例项目。", exampleMuseum: "博物馆红门（四人劫案）", exampleBakery: "面包店救援（五人营救）",
    assetBindCharacter: "绑定到角色资产", strictIdentityHint: "强锁定角色将自动进入 STRICT IDENTITY LOCK，编译时不可删除。",
    compileAssetId: "编译 (Asset-ID)", compileTarget: "编译模板", assetIdTemplate: "Asset-ID Tagged", proSequenceTemplate: "Pro Sequence", shotCardsTemplate: "Shot Cards", templatePlaceholder: "选择编译模板", targetModel: "目标模型", targetModelHint: "只决定提示词引用语法和输出模板，不决定 AI 对话模型", modelNone: "不指定（默认策略）", promptHistory: "版本历史", historyEmpty: "暂无版本，编译后自动存档", restore: "恢复", deleteVersion: "删除版本", manualOverride: "已手动覆写（结构化数据是唯一真源）", rebuild: "从结构重建", keepOverride: "保留覆写", versionRestored: "已从历史恢复结构。",
    saveProject: "保存工程", projectSaved: "已保存到 .cineprompt 工程目录：", projectSaveFallback: "桌面版未运行，已导出 JSON 备份。", projectLoaded: "已载入工程目录。", projectOpenInvalid: "所选目录不是有效的 .cineprompt 工程（缺少 project.json）。", aiFixLabel: "修复建议", aiGenerateBeats: "智能节拍建议", apiKeyLabel: "Provider API Key（存系统钥匙串）", apiKeyPlaceholder: "sk-…", saveKey: "保存 Key", keySavedKeychain: "已存入系统钥匙串。", keySavedLocal: "桌面版未运行，已存入浏览器本地（仅演示）。", keyHint: "API Key 仅存于系统 Keychain / Credential Manager，绝不写入工程文件或浏览器存储。", aiStatusTitle: "AI 辅助状态",
    apiSettings: "API 设置", chatModel: "Chat 模型", refreshModels: "刷新列表", noChatModels: "尚未配置 Chat 模型", noChatModelsHint: "请先在 LenTalk 设置的「自定义平台」中添加 Chat 模型，再回来选择。", aiProvider: "AI 服务商", providerNone: "本地模板建议（不调用远程）", providerOpenAI: "OpenAI", providerDeepSeek: "DeepSeek", providerMoonshot: "Kimi (Moonshot)", providerQwen: "通义千问", providerZhipu: "智谱 GLM", providerCustom: "自定义 (OpenAI 兼容)", baseUrl: "API 地址 Base URL", baseUrlPlaceholder: "https://api.openai.com/v1", modelName: "模型名称", modelPlaceholder: "gpt-4o-mini / deepseek-chat / qwen-plus…", apiKey: "API Key", testConnection: "测试连接", testingConnection: "测试中…", testOk: "连接成功：{model} ✓", testFailed: "连接失败：{error}", networkErrorHint: "网络请求失败：可能是浏览器跨域（CORS）拦截，或地址不可达，请检查地址后重试。", modelsTimeoutError: "拉取超时：接口响应较慢，请稍后重试。", aiRequestInterrupted: "请求中断或超时：接口响应较慢或连接被中止，请检查地址后重试。", fetchModels: "拉取模型", fetchingModels: "拉取中…", modelsFetched: "可用模型 {count} 个", modelsFetchedChatHint: "（已过滤图片/视频模型，仅语言模型）", modelsFetchFailed: "拉取失败：{error}", modelsEmpty: "该接口未返回可用模型，或没有可用的语言模型", modelsNeedUrl: "请先填写 API 地址", modelsFilterPlaceholder: "筛选模型…", pickModel: "点击选择模型", saveSettings: "保存设置", clearSettings: "清除选中的模型", settingsSaved: "已选择 Chat 模型，AI 辅助将调用 LenTalk 配置的远程模型。", settingsCleared: "已清除选中的 Chat 模型，AI 辅助回到本地模板建议。", settingsUsageTitle: "这个模型会用于哪里？", settingsUsageHint: "配置后，「智能模板建议 / 修复建议 / 节拍建议」会调用你在 LenTalk 中配置的大语言模型（地址与 Key 共用 LenTalk 设置），并返回可确认的结构化建议；提示词编译始终在本机完成。", settingsSecurityHint: "地址与 Key 与 LenTalk 共用同一份配置，不会在工作室里重复保存；请直接在 LenTalk「设置 → 自定义平台」中管理。", settingsModeLocal: "当前：本地模板建议", settingsModeRemote: "当前：{provider} · {model}", showKey: "显示 Key", hideKey: "隐藏 Key", aiProviderRemote: "远程模型", aiStatusBody: "配置 API 后，「智能模板建议 / 修复建议」会调用 OpenAI 兼容格式的大语言模型（OpenAI、DeepSeek、Kimi、通义千问、智谱 GLM 等）；未配置时使用本地模板建议。API Key 只保存在本机，不会写入工程文件。", cameraCountLabel: "相机", continuityOk: "通过",
    riskScore: "风险评分", riskOverall: "整体", riskLevelLow: "低风险", riskLevelMedium: "中风险", riskLevelHigh: "高风险", riskPerShot: "分镜头评分", fix: "修复", groupIdentity: "身份", groupSpatial: "空间", groupProp: "道具状态", groupCausality: "因果", groupTechnical: "技术", groupAudio: "音频", groupActing: "表演", groupOptics: "光学", groupCamera: "相机", groupDialogue: "对白", groupContext: "上下文", groupLighting: "光线", groupPhysics: "物理", issueError: "错误", issueWarning: "警告", issueInfo: "建议", fixed: "已修复。",
    preExportChecklist: "导出前清单", checklistPassed: "全部通过", checklistBlocked: "存在错误级问题", exportBlockedHint: "请先在连续性面板解决错误级问题再导出。", directorQuality: "导演文档质量",
    stagingLock: "场景站位", stagingAdjustParams: "画面调整参数", addFromAssets: "从资产添加", stagingChooseLocation: "选择地点资产", stagingNoLocationHint: "资产库中还没有地点资产，请先在右侧「资产库」创建地点。", stagingAddCharacter: "从资产添加角色", stagingChooseCharacter: "选择角色加入左到右排序", stagingNoCharacterHint: "资产库中还没有角色资产，请先在右侧「资产库」创建角色。", stagingAllCharactersAdded: "所有角色已加入排序", stagingCardEmpty: "点击设置地点资产与画面参数", stagingDone: "完成", locationAsset: "地点资产", spatialAnchor: "空间锚点", spatialAnchorPlaceholder: "所有人背靠红门旁的白色混凝土墙，滑板在脚边…", leftToRightOrder: "左到右排序", spacing: "人物间距", axisDirection: "180° 轴方向", priorContext: "前情续接", priorContextPlaceholder: "进入本场景前发生了什么，模型需要知道…", emptyOrderHint: "尚未设置排序，点击「+ 从资产添加角色」添加", moveLeft: "左移", moveRight: "右移", deleteParticipant: "移出站位",
    aiCompileScene: "AI 智能分镜", aiCompiling: "AI 分镜中…", aiCompilePrompt: "AI编译提示词", localCompile: "本地编译", aiCompileDone: "AI 已完成剧情分镜，并填入音频计划 / 镜头列表 / 检查器 / 提示词编辑器。", aiCompileFailed: "AI 智能分镜失败：", copyAiError: "复制错误信息", aiErrorCopied: "错误信息已复制。", promptLocalCompiled: "已本地编译，提示词已输出到提示词编辑器。",
    participants: "参与角色", addParticipant: "添加角色", emptyParticipantsHint: "从资产库选择角色加入本镜头，可多选（最多 8 人）。", role: "画面职责", rolePrimary: "主要", roleSupporting: "次要", roleTarget: "目标", roleBackground: "背景", position: "前中后景", positionForegroundLeft: "前景左", positionCenter: "中央", positionBackgroundRight: "背景右", positionCenterLeft: "中左", positionCenterRight: "中右", entrance: "入画方式", entranceAlready: "已在画内", entranceLeft: "从左侧入画", entranceRight: "从右侧入画", facing: "朝向", facingCamera: "朝向镜头", facingProfileLeft: "左侧面", facingProfileRight: "右侧面", facingCenter: "朝画面中心", eyeline: "视线", useSceneStaging: "使用场景站位", intentionalAxisBreak: "故意越轴", axisNotePlaceholder: "说明为什么越轴…", layoutAnchorPlaceholder: "镜头级空间锚点（覆盖场景）…", dragHint: "拖动排序，或使用箭头",
    shotStates: "状态", startStates: "开始状态", endStates: "结束状态", stateAsset: "资产", stateLabel: "状态", holder: "持有者", statePosition: "位置", addState: "添加状态", stateInheritedHint: "未设置时自动继承上一镜头结束状态", stateFirstShotHint: "首镜初始状态，从这开始建立状态链", stateCustom: "自定义状态…", stateAssetPlaceholder: "选择道具 / 角色 / 地点", stateHolderPlaceholder: "持有者（可选）",
    beats: "节拍", addBeat: "添加节拍", actor: "执行者", target: "目标", targetNone: "无目标", targetCharacter: "角色", targetProp: "道具", bodyPart: "身体部位", bodyPartPlaceholder: "如 right forearm / head…", stateBefore: "前置状态", stateAfter: "后置状态", dialogue: "对白", requiredBeat: "强制发生", forbiddenTargets: "禁止目标", cutRule: "剪切规则", cutRulePlaceholder: "如 cut exactly when GUARD begins to fall", beatSplitAdvice: "检测到 3 次以上焦段切换，建议将本镜头拆为 Sub-shot 或新镜头", moveUp: "上移", moveDown: "下移", beatDuration: "时长(秒)", actorMustParticipant: "执行者默认取当前镜头参与角色",
    characterSheet: "人物三视图", voiceTone: "声音音色", prop: "道具", propPlaceholder: "道具用法描述，如：左手拿红色包包", propImageUploaded: "道具图片已上传。",
    characterDesc: "人物描述", characterDescPlaceholder: "外貌、体态、标志特征…", characterAdded: "已添加角色。", characterName: "角色名称", none: "无",
    emptyCharacters: "点击添加角色", deleteCharacter: "删除角色", editDesc: "编辑人物描述", noDesc: "未填写，点击添加", save: "保存", cancel: "取消", editProp: "编辑道具", addProp: "添加道具", propDescPlaceholder: "道具用法描述，如：左手拿红色包包", characterDeleted: "角色已删除。", propAdded: "已添加道具。", propDeleted: "道具已删除。", editDetails: "编辑详情", characterDetails: "角色详情", loglineTitle: "故事梗概", loglinePlaceholder: "用一句话概括这段场景的核心情节…", shootingMode: "拍摄模式", shootingModeLongTake: "长镜头", shootingModeLongTakeHint: "全镜统一相机参数", shootingModeMultiShot: "多镜头", shootingModeMultiShotHint: "各镜可更换机位", deleteShot: "删除镜头", deleteBeat: "删除节拍", deleteObjective: "删除目标", collapse: "收起", duration: "时长", startSec: "开始(秒)", endSec: "结束(秒)", roleSummaryHint: "个角色资产已绑定，详情见下方「资产库」",
    technicalProfile: "风格配方", applyRecipe: "大师风格 / 风格配方", recipeNone: "自定义风格", preset: "预设", custom: "自定义补充", lockModule: "锁定（配方不覆盖）", moduleFormat: "影像格式", moduleFilm: "胶片/色彩科学", moduleFrame: "帧率/快门", moduleCinematography: "摄影语言", moduleLighting: "光线", moduleColor: "色彩", moduleActing: "表演", moduleSkin: "皮肤", modulePhysics: "物理", moduleComposition: "构图", moduleSharpness: "锐化", moduleHint: "点击配方卡片选择风格；双击或点右下角铅笔进入编辑；自定义风格默认所有选项为「无」，可自行选择需要的搭配。", recipeCombo: "组合配方", editRecipe: "编辑配方", pickRecipe: "选择风格配方", recipeActive: "使用中", recipeEditHint: "逗号分隔各项；保存后覆盖当前配方字段（锁定的模块除外）。",
    briefing: "导演简报", storyGroup: "剧情", styleGroup: "风格倾向", styleBrief: "一句风格话", styleBriefPlaceholder: "用一句话描述想要的影像风格，AI 会据此展开…", constraintGroup: "硬约束", mustHappen: "必须发生", mustHappenPlaceholder: "每行一条，一定要发生的可见事件…", forbidLabel: "禁止发生", forbidPlaceholder: "每行一条，绝不能出现的画面或事件…", emotionArc: "情绪走向", emotionArcPlaceholder: "情绪如何演进，只写可见行为…", dialoguePlaceholder: "本场景对白 / 台词（可选）…",
    addBlankShot: "空白镜头", templateApplied: "已应用镜头模板。", templateRequired: "必填项", cutStyle: "时间关系", cutHard: "硬切", cutOverlap: "允许重叠", cutMatch: "匹配剪辑",
    audioPlan: "音频计划", diegeticMusic: "画内音乐", sfx: "环境音效", score: "配乐", scoreNone: "无", scoreOriginal: "原创配乐", subtitles: "字幕", subtitlesNone: "无", subtitlesBurned: "烧录字幕", musicSource: "来源道具", addItem: "添加", audioHint: "画内音乐需与 SFX 分开填写；来源道具从资产库选择。", audioExpand: "展开", audioCollapse: "收起", voiceClip: "声音音色", voiceUploadHint: "点击上传音频（mp3 / wav / m4a）", voiceUploaded: "声音音色已上传。", voiceUploadFailed: "音频上传失败。",
    identityAppearance: "身份 · 外观", actingMasterProfile: "表演母版", actingMasterPlaceholder: "身体传记：\n心理引擎：\n声线：\n习惯/抽动（带触发条件）：\n命名步态：\n压力裂缝（However, when X…）：\n软化目标（最多一个）：", voicePromptLabel: "声音锁", voicePromptPlaceholder: "例：35 岁、北方口音。低沉沙哑；语速慢、字字清晰；压力下会加快并吞字。", performanceTarget: "表演目标（0–5）", performanceTargetHint: "0 假人 · 1 朗诵 · 2 勤勉 · 3 匠人 · 4 鲜活（默认）· 5 磁铁。数字越高，表演越立体、越可被镜头捕捉；低于 4 建议重写表演母版。", perf0: "0", perf1: "1", perf2: "2", perf3: "3", perf4: "4", perf5: "5", perf0Tip: "0 假人：无表情、无动机的静态表演", perf1Tip: "1 朗诵：只会念台词，缺动作与反应", perf2Tip: "2 勤勉：认真但机械，动作到位却无内心", perf3Tip: "3 匠人：技术准确、层次分明的表演", perf4Tip: "4 鲜活（默认）：有动机、有变化、可被镜头捕捉", perf5Tip: "5 磁铁：同时演奏两种相反真相（特写级高难度）", directorDocument: "导演文档", directorLayersHint: "AI 编译后生成的导演级分层文档；展开可逐层编辑，锁定后再次 AI 编译不会被覆盖。", lockLayer: "锁定此层", unlockLayer: "解除锁定", directorLayerEmpty: "该层尚未生成，可手动填写。",
    actingObjectives: "表演目标", objective: "目的", objectivePlaceholder: "动词 + 指向对象，如「让列车长承认延误」", superObjective: "贯穿目标", superObjectivePlaceholder: "全剧反复出现的深层欲望（可留空）", obstacle: "阻碍", obstaclePlaceholder: "外在或内在挡路的东西", stakes: "失败代价", stakesPlaceholder: "失败后他会失去什么（必须让角色害怕）", noCharacterObjectiveHint: "先把角色加入场景站位，再为每个角色填写表演目标。", shotPerformanceLevel: "表演评分（0–5）", shotEyeLife: "眼部生活", shotEyeLifePlaceholder: "微扫视 / 眨眼质量 / 瞳光 / 眼睛先于转头…", beatTactic: "策略", beatTacticPlaceholder: "本拍用什么手段，如 press / charm / provoke", beatSubtext: "潜台词", beatSubtextPlaceholder: "与台词相反的真实意图", beatBeatChange: "节拍变化", beatBeatChangePlaceholder: "可见行为变化：停顿 / 姿势 / 语速 / 视线切换", beatReaction: "反应先于台词结束", beatReactionPlaceholder: "对方话没说完就开始的反应",
  },
  en: {
    project: "Project", newProject: "New project", scenes: "Scenes", addScene: "Add scene", character: "Character", addCharacter: "Add character", reference: "Reference", addReference: "Add reference", localProject: "Local project", saved: "Saved",
    openProject: "Open project", settings: "Settings", compilePrompt: "Compile prompt", environmentLocked: "Environment locked", referenceEnvironment: "Reference / Environment", previewScene: "Preview scene", shotList: "Shot list", cuts: "cuts", addShot: "Add shot",
    inspector: "Inspector", noShot: "No shot selected", camera: "Camera", cameraModel: "Camera model", framing: "Framing", lens: "Lens", lensModel: "Lens model", movement: "Movement", performance: "Performance", action: "Action", acting: "Acting", continuity: "Continuity", characterLocked: "Character locked", screenDirection: "Screen direction",
    promptEditor: "Prompt editor", localCompiler: "Local compiler", copyPrompt: "Copy prompt", export: "Export", generate: "Generate", addShotHint: "Add a shot to begin shot-level design.", promptCopied: "Prompt copied to clipboard.", promptCompiled: "Structured prompt compiled.", promptRebuilt: "Prompt rebuilt from structured fields.", newProjectCreated: "New project created.", projectImported: "Project imported.", invalidProject: "That file is not a valid CinePrompt JSON export.", addCharacterHint: "Character creation is prepared for the next iteration.", addReferenceHint: "Drop-in reference analysis will connect to the AI provider layer.",
    untitledFilm: "Untitled film", sceneName: "Scene", newSceneName: "New Scene", shotName: "Shot", defineAction: "Define the action.", naturalPerformance: "Natural, restrained performance.", environment: "Environment", weather: "Weather", movementDirection: "Movement direction",
    static: "Static", handheld: "Handheld", steadicam: "Steadicam", dolly: "Dolly", tracking: "Tracking", crane: "Crane", directionLTR: "left-to-right", directionRTL: "right-to-left",
    projectName: "Project name", masterStyle: "Master style", selectStyle: "Select a master style", uploadImage: "Upload image", replaceImage: "Replace image", uploadAudio: "Upload audio", imageUploaded: "Character image uploaded.", audioUploaded: "Character audio uploaded.", uploadFailed: "Failed to read file, please retry.", metaLocation: "Location", metaTime: "Time", metaWeather: "Weather", metaDuration: "Duration", negativePrompt: "Negative prompt", negativeHint: "Leave empty for default constraints", negativePlaceholder: "Elements you do not want in the frame, comma-separated…",
    sceneLock: "Scene lock", notes: "Notes", notesPlaceholder: "Environment details, mood, props…", deleteScene: "Delete scene", seconds: "s", keepOneScene: "Keep at least one scene.",
    assetLibrary: "Asset Library", assetTabCharacter: "Characters", assetTabLocation: "Locations", assetTabProp: "Props", assetTabReference: "Style / Audio Ref", addAsset: "Add asset", emptyAssets: "The asset library is empty. Click “+ Add” to create a character, location, or prop.",
    assetName: "Name", assetNamePlaceholder: "REIN / BAKERY INTERIOR / boombox", assetNotes: "User notes (AI reference only)", assetNotesPlaceholder: "Add personality, motivation, voice, or asset usage; never exported to the final prompt…", assetNotesZhPlaceholder: "Add notes in Chinese; used only as AI reference and never exported to the final prompt…", assetDescription: "Description (canonical EN)", assetDescriptionPlaceholder: "Type or paste the English description, e.g. Slim woman in a vintage bomber jacket.",
    assetDescriptionZh: "Chinese description", assetDescriptionZhPlaceholder: "Describe this image in Chinese (AI will fill Chinese + canonical English from the reference)…", aiFillDetails: "AI fill details", aiFillDone: "AI filled the card from the reference image; fine-tune as needed.", aiFillFailed: "AI fill failed: ", aiNotConfigured: "Configure a language model under Settings → API Settings before using AI fill.", aiFillNeedsImage: "Upload at least one reference image first — the AI needs it to fill details.",
    useFor: "Use for", useForFace: "Face identity", useForBody: "Body type", useForWardrobe: "Wardrobe", useForPropAppearance: "Prop appearance", useForEnvironment: "Environment layout", useForAppearanceOnly: "Appearance only",
    ignoreLabel: "Ignore", ignorePose: "Pose", ignoreBackground: "Background", ignoreLighting: "Lighting", ignoreComposition: "Composition", ignoreExpression: "Expression",
    lockLevel: "Lock level", lockNone: "No lock", lockSoft: "Soft lock", lockStrict: "Strict lock",
    uniqueMarkers: "Unique markers", uniqueMarkerPlaceholder: "scar on left eye only (Enter to add)", alwaysVisible: "Always visible", alwaysVisiblePlaceholder: "black leather gloves on both hands at all times (Enter to add)",
    deleteAsset: "Delete asset", assetAdded: "Asset added.", assetDeleted: "Asset deleted.", assetKindCharacter: "Character", assetKindLocation: "Location", assetKindProp: "Prop", assetKindStyleRef: "Style ref", assetKindAudioRef: "Audio ref",
    referenceImage: "Reference image", replaceReference: "Replace reference", identityLockSection: "Identity locks", characterCountLock: "Character count lock", countLockPlaceholder: "Not locked", openExample: "Load example", exampleLoaded: "Example project loaded.", exampleMuseum: "Museum Red Doors (heist of four)", exampleBakery: "Bakery Rescue (rescue of five)",
    assetBindCharacter: "Bind to character asset", strictIdentityHint: "Strict-locked characters enter STRICT IDENTITY LOCK and cannot be removed from the compiled prompt.",
    compileAssetId: "Compile (Asset-ID)", compileTarget: "Compile template", assetIdTemplate: "Asset-ID Tagged", proSequenceTemplate: "Pro Sequence", shotCardsTemplate: "Shot Cards", templatePlaceholder: "Choose template", targetModel: "Target model", targetModelHint: "Controls prompt syntax and output template only; it does not select the AI chat model", modelNone: "Unspecified (default strategy)", promptHistory: "History", historyEmpty: "No versions yet; compiling auto-archives", restore: "Restore", deleteVersion: "Delete version", manualOverride: "Manually overridden (structured data is the single source of truth)", rebuild: "Rebuild", keepOverride: "Keep override", versionRestored: "Structure restored from history.",
    saveProject: "Save project", projectSaved: "Saved to .cineprompt project directory:", projectSaveFallback: "Desktop shell not running; exported JSON instead.", projectLoaded: "Project directory loaded.", projectOpenInvalid: "Not a valid .cineprompt project (project.json missing).", aiFixLabel: "Fix advice", aiGenerateBeats: "Smart beat advice", apiKeyLabel: "Provider API Key (system keychain)", apiKeyPlaceholder: "sk-…", saveKey: "Save key", keySavedKeychain: "Saved to system keychain.", keySavedLocal: "Desktop shell not running; stored in browser storage (demo only).", keyHint: "API keys live only in the system Keychain / Credential Manager, never in project files or browser storage.", aiStatusTitle: "AI assistant status",
    apiSettings: "API Settings", chatModel: "Chat model", refreshModels: "Refresh", noChatModels: "No Chat models configured", noChatModelsHint: "Add a Chat model in LenTalk Settings → Custom platforms, then come back and pick one here.", aiProvider: "AI Provider", providerNone: "Local template advice (no remote calls)", providerOpenAI: "OpenAI", providerDeepSeek: "DeepSeek", providerMoonshot: "Kimi (Moonshot)", providerQwen: "Qwen (DashScope)", providerZhipu: "Zhipu GLM", providerCustom: "Custom (OpenAI-compatible)", baseUrl: "Base URL", baseUrlPlaceholder: "https://api.openai.com/v1", modelName: "Model", modelPlaceholder: "gpt-4o-mini / deepseek-chat / qwen-plus…", apiKey: "API Key", testConnection: "Test connection", testingConnection: "Testing…", testOk: "Connected: {model} ✓", testFailed: "Connection failed: {error}", networkErrorHint: "Network request failed: the browser may have blocked the cross-origin request (CORS), or the address is unreachable. Check the URL and retry.", modelsTimeoutError: "Model list request timed out; the endpoint is slow, please retry.", aiRequestInterrupted: "Request interrupted or timed out: the endpoint is slow or the connection was aborted; check the URL and retry.", fetchModels: "Fetch models", fetchingModels: "Fetching…", modelsFetched: "{count} models available", modelsFetchedChatHint: " (image/video models filtered; language models only)", modelsFetchFailed: "Fetch failed: {error}", modelsEmpty: "No models returned, or no language model available", modelsNeedUrl: "Enter Base URL first", modelsFilterPlaceholder: "Filter models…", pickModel: "Click to select a model", saveSettings: "Save settings", clearSettings: "Clear selection", settingsSaved: "Chat model selected. AI assistance will use the remote model configured in LenTalk.", settingsCleared: "Chat model cleared. AI assistance is back to local template advice.", settingsUsageTitle: "Where is this model used?", settingsUsageHint: "Once configured, smart template advice / continuity fix advice / beat advice calls the LLM configured in LenTalk (same base URL and API key), and returns confirmable structured suggestions; prompt compilation always runs locally.", settingsSecurityHint: "Base URL and API key are shared with LenTalk's settings and never duplicated here; manage them in LenTalk Settings → Custom platforms.", settingsModeLocal: "Current: local template advice", settingsModeRemote: "Current: {provider} · {model}", showKey: "Show key", hideKey: "Hide key", aiProviderRemote: "Remote model", aiStatusBody: "Once API is configured, smart template advice / fix advice calls an OpenAI-compatible LLM (OpenAI, DeepSeek, Kimi, Qwen, Zhipu GLM and more). Without config it uses local template advice. The API key stays on this machine and is never written into project files.", cameraCountLabel: "Camera", continuityOk: "OK",
    riskScore: "Risk score", riskOverall: "Overall", riskLevelLow: "Low risk", riskLevelMedium: "Medium risk", riskLevelHigh: "High risk", riskPerShot: "Per-shot scores", fix: "Fix", groupIdentity: "Identity", groupSpatial: "Spatial", groupProp: "Prop states", groupCausality: "Causality", groupTechnical: "Technical", groupAudio: "Audio", groupActing: "Acting", groupOptics: "Optics", groupCamera: "Camera", groupDialogue: "Dialogue", groupContext: "Context", groupLighting: "Lighting", groupPhysics: "Physics", issueError: "Error", issueWarning: "Warning", issueInfo: "Info", fixed: "Fixed.",
    preExportChecklist: "Pre-export checklist", checklistPassed: "All passed", checklistBlocked: "Error-level issues present", exportBlockedHint: "Resolve error-level issues in the continuity panel before exporting.", directorQuality: "Director document quality",
    stagingLock: "Scene staging", stagingAdjustParams: "Picture adjustment", addFromAssets: "Add from assets", stagingChooseLocation: "Choose a location asset", stagingNoLocationHint: "No location assets yet — create a location in the Asset Library on the right first.", stagingAddCharacter: "Add characters from assets", stagingChooseCharacter: "Choose characters to join the left-to-right order", stagingNoCharacterHint: "No character assets yet — create characters in the Asset Library on the right first.", stagingAllCharactersAdded: "All characters are already in the order", stagingCardEmpty: "Click to set the location asset and picture parameters", stagingDone: "Done", locationAsset: "Location asset", spatialAnchor: "Spatial anchor", spatialAnchorPlaceholder: "All four have their backs against the white concrete wall beside the red doors; skateboards at their feet…", leftToRightOrder: "Left-to-right order", spacing: "Spacing", axisDirection: "180° axis", priorContext: "Prior context", priorContextPlaceholder: "What happened before this scene that the model needs to know…", emptyOrderHint: "No order set yet — click “+ Add characters from assets” to add", moveLeft: "Move left", moveRight: "Move right", deleteParticipant: "Remove from layout",
    aiCompileScene: "AI storyboard", aiCompiling: "AI storyboarding…", aiCompilePrompt: "AI compile prompt", localCompile: "Compile locally", aiCompileDone: "AI completed the storyboard and filled the audio plan, shot list, inspector, and prompt editor.", aiCompileFailed: "AI storyboard failed: ", copyAiError: "Copy error details", aiErrorCopied: "Error details copied.", promptLocalCompiled: "Prompt compiled locally and written to the editor.",
    participants: "Participants", addParticipant: "Add character", emptyParticipantsHint: "Pick characters from the asset library to join this shot (up to 8).", role: "Role", rolePrimary: "Primary", roleSupporting: "Supporting", roleTarget: "Target", roleBackground: "Background", position: "Position", positionForegroundLeft: "Foreground left", positionCenter: "Center", positionBackgroundRight: "Background right", positionCenterLeft: "Center left", positionCenterRight: "Center right", entrance: "Entrance", entranceAlready: "Already in frame", entranceLeft: "Enters left", entranceRight: "Enters right", facing: "Facing", facingCamera: "Toward camera", facingProfileLeft: "Profile left", facingProfileRight: "Profile right", facingCenter: "Toward center", eyeline: "Eyeline", useSceneStaging: "Use scene staging", intentionalAxisBreak: "Intentional axis break", axisNotePlaceholder: "Explain why the axis is broken…", layoutAnchorPlaceholder: "Shot-level spatial anchor (overrides scene)…", dragHint: "Drag to reorder, or use arrows",
    shotStates: "States", startStates: "Start states", endStates: "End states", stateAsset: "Asset", stateLabel: "State", holder: "Holder", statePosition: "Position", addState: "Add state", stateInheritedHint: "Auto-inherits from previous shot end when unset", stateFirstShotHint: "Initial state for the first shot; start the state chain here", stateCustom: "Custom state…", stateAssetPlaceholder: "Pick a prop / character / location", stateHolderPlaceholder: "Holder (optional)",
    beats: "Beats", addBeat: "Add beat", actor: "Actor", target: "Target", targetNone: "No target", targetCharacter: "Character", targetProp: "Prop", bodyPart: "Body part", bodyPartPlaceholder: "e.g. right forearm / head…", stateBefore: "Before", stateAfter: "After", dialogue: "Dialogue", requiredBeat: "Required", forbiddenTargets: "Never target", cutRule: "Cut rule", cutRulePlaceholder: "e.g. cut exactly when GUARD begins to fall", beatSplitAdvice: "3+ framing switches detected; consider splitting this shot into sub-shots or a new shot", moveUp: "Move up", moveDown: "Move down", beatDuration: "Duration (s)", actorMustParticipant: "Actor options come from this shot's participants",
    characterSheet: "Character sheet", voiceTone: "Voice tone", prop: "Prop", propPlaceholder: "Prop usage, e.g. holding a red handbag in left hand", propImageUploaded: "Prop image uploaded.",
    characterDesc: "Character description", characterDescPlaceholder: "Appearance, physique, signature features…", characterAdded: "Character added.", characterName: "Character name", none: "None",
    emptyCharacters: "Click to add character", deleteCharacter: "Delete character", editDesc: "Edit character description", noDesc: "Not filled, click to add", save: "Save", cancel: "Cancel", editProp: "Edit prop", addProp: "Add prop", propDescPlaceholder: "Prop usage, e.g. holding a red handbag in left hand", characterDeleted: "Character deleted.", propAdded: "Prop added.", propDeleted: "Prop deleted.", editDetails: "Edit details", characterDetails: "Character details", loglineTitle: "Logline", loglinePlaceholder: "Summarize the core of this scene in one sentence…", shootingMode: "Shooting mode", shootingModeLongTake: "Long take", shootingModeLongTakeHint: "Unified camera across shots", shootingModeMultiShot: "Multi-shot", shootingModeMultiShotHint: "Camera may change per shot", deleteShot: "Delete shot", deleteBeat: "Delete beat", deleteObjective: "Delete objective", collapse: "Collapse", duration: "Duration", startSec: "Start (s)", endSec: "End (s)", roleSummaryHint: "character assets bound. See the Asset Library below for details.",
    technicalProfile: "Style recipes", applyRecipe: "Master style / recipe", recipeNone: "Custom style", preset: "Preset", custom: "Custom", lockModule: "Lock (recipe won't override)", moduleFormat: "Format", moduleFilm: "Film stock", moduleFrame: "Frame rate", moduleCinematography: "Cinematography", moduleLighting: "Lighting", moduleColor: "Color", moduleActing: "Acting", moduleSkin: "Skin", modulePhysics: "Physics", moduleComposition: "Composition", moduleSharpness: "Sharpness", moduleHint: "Click the recipe card to pick a style; double-click or the pencil icon edits it; Custom style starts with all options empty so you can pick your own combination.", recipeCombo: "Combination recipes", editRecipe: "Edit recipe", pickRecipe: "Pick a style recipe", recipeActive: "Active", recipeEditHint: "Separate items with commas; saving overrides the current recipe fields (locked modules are kept).",
    briefing: "Director brief", storyGroup: "Story", styleGroup: "Style direction", styleBrief: "One-line style", styleBriefPlaceholder: "Describe the visual style in one sentence; AI expands it…", constraintGroup: "Hard constraints", mustHappen: "Must happen", mustHappenPlaceholder: "One per line — events that must visibly happen…", forbidLabel: "Forbid", forbidPlaceholder: "One per line — visuals or events that must never appear…", emotionArc: "Emotion arc", emotionArcPlaceholder: "How the emotion evolves, visible behavior only…", dialoguePlaceholder: "Scene dialogue / lines (optional)…",
    addBlankShot: "Blank shot", templateApplied: "Shot template applied.", templateRequired: "Required fields", cutStyle: "Cut style", cutHard: "Hard cut", cutOverlap: "Overlap", cutMatch: "Match cut",
    audioPlan: "Audio plan", diegeticMusic: "Diegetic music", sfx: "SFX", score: "Score", scoreNone: "None", scoreOriginal: "Original score", subtitles: "Subtitles", subtitlesNone: "None", subtitlesBurned: "Burned-in", musicSource: "Source prop", addItem: "Add", audioHint: "Keep diegetic music separate from SFX; pick the source prop from the asset library.", audioExpand: "Expand", audioCollapse: "Collapse", voiceClip: "Voice clip", voiceUploadHint: "Click to upload audio (mp3 / wav / m4a)", voiceUploaded: "Voice clip uploaded.", voiceUploadFailed: "Audio upload failed.",
    identityAppearance: "Identity · Appearance", actingMasterProfile: "Acting master profile", actingMasterPlaceholder: "Body biography:\nPsychological engine:\nVocal profile:\nHabit / tic (trigger):\nNamed gait:\nMask + crack (However, when X…):\nSoftening goal (max one):", voicePromptLabel: "Voice lock", voicePromptPlaceholder: "e.g. A 35-year-old with a northern accent. Low, raspy register; slow, deliberate delivery; speeds up and swallows words under pressure.", performanceTarget: "Performance target (0–5)", performanceTargetHint: "0 Mannequin · 1 Reciting · 2 Diligent · 3 Craftsman · 4 Alive (default) · 5 Magnet. Higher numbers give deeper, more camera-readable performances; rewrite the master profile if below 4.", perf0: "0", perf1: "1", perf2: "2", perf3: "3", perf4: "4", perf5: "5", perf0Tip: "0 Mannequin: expressionless, unmotivated static performance", perf1Tip: "1 Reciting: lines only, no action or reaction", perf2Tip: "2 Diligent: earnest but mechanical, action without inner life", perf3Tip: "3 Craftsman: technically precise, layered performance", perf4Tip: "4 Alive (default): motivated, changing, camera-readable", perf5Tip: "5 Magnet: plays two opposite truths at once (high-difficulty close-up)", directorDocument: "Director document", directorLayersHint: "Layered director document produced by AI compile; expand to edit each layer, lock to preserve on recompile.", lockLayer: "Lock this layer", unlockLayer: "Unlock", directorLayerEmpty: "Not generated yet; type to fill.",
    actingObjectives: "Performance objectives", objective: "Objective", objectivePlaceholder: "Verb + target, e.g. get the conductor to admit the delay", superObjective: "Super-objective", superObjectivePlaceholder: "Deep recurring desire across the whole story (optional)", obstacle: "Obstacle", obstaclePlaceholder: "What stands in the way, internal or external", stakes: "Stakes", stakesPlaceholder: "What he loses on failure (must frighten the character)", noCharacterObjectiveHint: "Add characters to the scene staging first, then set each character's performance objective.", shotPerformanceLevel: "Performance level (0–5)", shotEyeLife: "Eye life", shotEyeLifePlaceholder: "Micro glances / blink quality / eye glint / eyes leading the turn…", beatTactic: "Tactic", beatTacticPlaceholder: "The means of this beat, e.g. press / charm / provoke", beatSubtext: "Subtext", beatSubtextPlaceholder: "The true intent opposite to the line", beatBeatChange: "Beat change", beatBeatChangePlaceholder: "Visible shift: pause / posture / tempo / eye-line cut", beatReaction: "Reaction before line ends", beatReactionPlaceholder: "Reaction that starts before the other speaker finishes",
  }
} as const;

export const cameraLabels: Record<Locale, Record<string, string>> = {
  zh: { Static: "固定", Handheld: "手持", Steadicam: "斯坦尼康", Dolly: "移轨", Tracking: "跟拍", Crane: "摇臂", POV: "主观镜头", OTS: "过肩镜头" },
  en: { Static: "Static", Handheld: "Handheld", Steadicam: "Steadicam", Dolly: "Dolly", Tracking: "Tracking", Crane: "Crane", POV: "POV", OTS: "OTS" }
};

export const framingLabels: Record<Locale, Record<string, string>> = {
  zh: { Wide: "全景", "3/4 medium, behind subject": "3/4 中景，人物背后", "Medium close-up": "中近景", "Extreme close-up, profile": "极近特写，侧面" },
  en: { Wide: "Wide", "3/4 medium, behind subject": "3/4 medium, behind subject", "Medium close-up": "Medium close-up", "Extreme close-up, profile": "Extreme close-up, profile" }
};

export const continuityLabels: Record<string, keyof typeof copy.zh> = { Environment: "environment", Weather: "weather", "Movement direction": "movementDirection" };

/** 天气下拉选项 */
export const weatherOptions: Record<Locale, string[]> = {
  zh: ["晴朗", "多云", "阴天", "小雨", "暴雨", "雷雨", "雪", "雾", "大风"],
  en: ["Sunny", "Partly cloudy", "Overcast", "Light rain", "Heavy rain", "Thunderstorm", "Snow", "Fog", "Windy"]
};

/** 时间下拉选项 */
export const timeOptions: Record<Locale, string[]> = {
  zh: ["黎明", "清晨", "上午", "中午", "下午", "傍晚", "黄昏", "夜晚", "深夜", "凌晨"],
  en: ["Dawn", "Early morning", "Morning", "Noon", "Afternoon", "Dusk", "Sunset", "Night", "Late night", "Midnight"]
};
// (no-op for marker)
